name: angel_seeder
description: Straightforward data seeder for Angel services.
version: 1.0.2
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/seeder
dependencies:
    angel_framework: ^1.0.0-dev
    faker: ^0.0.4
dev_dependencies:
    test: ^0.12.0
